name: Deploy Automático 

on:  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # ou 'adopt', 'zulu', etc.
          java-version: '17'

      - name: Buildar o Projeto com Maven
        run: mvn clean package

      - name: Cria um arquivo temporário para a chave privada 
        run: |
          echo "${{ secrets.KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

      - name: Criando a pasta do app web e acertando o diretório
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.USER }}@${{ secrets.HOST }} \
          sudo mkdir -p /home/${{ secrets.USER }}/javaweb

      - name: Ajustar as permissões no servidor
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.USER }}@${{ secrets.HOST }} "sudo chown -R ${{ secrets.USER }}:${{ secrets.USER }} /home/${{ secrets.USER }}/javaweb && sudo chmod -R 755 /home/${{ secrets.USER }}/javaweb"
                      
      - name: Transferindo os arquivos da aplicação para o servidor
        run: |
          scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null target/web-0.0.1-SNAPSHOT.jar ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/javaweb

      - name: Iniciando a nova aplicação
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.USER }}@${{ secrets.HOST }} \
          "sudo java -jar /home/${{ secrets.USER }}/javaweb/web-0.0.1-SNAPSHOT.jar &"

      - name: Restartando o Serviço no Linux
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.USER }}@${{ secrets.HOST }} \
          sudo systemctl restart webapp.service

      - name: Limpa o arquivo de chave da chave privada após uso
        run: |
          rm /tmp/private_key
